dist: trusty
sudo: required

env:
  global:
    - NODE_VERSION=10.8
    - GO_VERSION=1.7
    - LOGLEVEL=info

before_install:
  - pushd ./scalerui-release/src/scalerui && source .envrc && popd

install:
  - npm install npm@latest -g
  - nvm install $NODE_VERSION
  - eval "$(gimme $GO_VERSION)"
  - go get github.com/onsi/ginkgo/ginkgo

before_script:
  - nvm use $NODE_VERSION
script:
  # Unit test
  - pushd ./scalerui-release/src/scalerui/view
  - npm install
  - npm run build
  - npm run test:coverage -- -u
  - popd
  - pushd ./scalerui-release/src/scalerui/src/scalerui
  - ginkgo -r -race -randomizeAllSpecs
  - popd
